### ISSUE TITLE
TODO: reduce dashboard container height

### ISSUE THREAD

**Issue by urain39** [urain39/yaaw-zh-hans#8]
https://github.com/urain39/yaaw-zh-hans/blob/e6a9d1756899eccb41a4b4fe3e143855e022d117/index.html#L83

```css
#not-selected-grp {
    float: right;
}
```
